modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="myserveriscompatible"
version="${file.jarVersion}"
displayName="MyServerIsCompatible"
authors="Focamacho"
description='''
Client-side mod to disable Forge's "Incompatible FML Modded Server" message.
'''
[[dependencies.myserveriscompatible]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.81,)"
    ordering="NONE"
    side="BOTH"