modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
[[mods]]
modId="myserveriscompatible"
version="${mod_version}"
displayName="MyServerIsCompatible"
authors="focamacho"
description='''
Client-side mod to disable Forge's "Incompatible FML Modded Server" message.
'''
[[dependencies.myserveriscompatible]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.13,)"
    ordering="NONE"
    side="BOTH"